{
 "title": "Ambiente",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature casa",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_item",
     "groupBy": [
      { "params": [ "item" ], "type": "tag" }
     ],
     "measurement": "ambiente",
     "query": "SELECT moving_average(\"value\", 10) FROM \"ambiente\" WHERE (\"misura\" = 'Temperatura' AND \"piano\" != 'EX'  AND \"stanza\" != '') AND $timeFilter GROUP BY \"item\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "misura", "operator": "=", "value": "Temperatura" },
      { "condition": "AND", "key": "piano", "operator": "!=", "value": "EX" }
     ]
    }
   ]
  },
  {
   "title": "Umidità casa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_item",
     "groupBy": [
      { "params": [ "item" ], "type": "tag" }
     ],
     "measurement": "ambiente",
     "query": "SELECT moving_average(\"value\", 10) FROM \"ambiente\" WHERE (\"misura\" = 'Umidita' AND \"stanza\" != '') AND $timeFilter GROUP BY \"item\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "misura", "operator": "=", "value": "Umidita" }
     ]
    }
   ]
  },
  {
   "title": "Sensore crepuscolare",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sensore crepuscolare",
     "measurement": "ambiente",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "misura", "operator": "=", "value": "Luminanza" },
      {
       "condition": "AND",
       "key": "item",
       "operator": "=",
       "value": "ptEXStazioneMeteoSensoreCrepuscolare"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperatura esterna",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperatura esterna",
     "measurement": "ambiente",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "misura", "operator": "=", "value": "Temperatura" },
      {
       "condition": "AND",
       "key": "item",
       "operator": "=",
       "value": "ptEXStazioneMeteoTemperaturaEsterno"
      }
     ]
    }
   ]
  },
  {
   "title": "Rilevamento GAS Cucina",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Gas Cucina",
     "measurement": "ambiente",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "misura", "operator": "=", "value": "Gas" },
      { "condition": "AND", "key": "item", "operator": "=", "value": "ptPTCucinaRilevamentoGas" }
     ]
    }
   ]
  }
 ]
}