{
 "title": "Network",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "STATUS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_item",
       "groupBy": [
        { "params": [ "item" ], "type": "tag" }
       ],
       "measurement": "network_online",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dispositivi Esterni / Seminterrato",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_item",
       "groupBy": [
        { "params": [ "item" ], "type": "tag" }
       ],
       "measurement": "network_ping",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         }
        ]
       ],
       "tags": [
        { "key": "piano", "operator": "=", "value": "EX" },
        { "condition": "OR", "key": "piano", "operator": "=", "value": "PS" }
       ]
      }
     ]
    },
    {
     "title": "Dispositivi Primo Piano",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_item",
       "groupBy": [
        { "params": [ "item" ], "type": "tag" }
       ],
       "measurement": "network_ping",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         }
        ]
       ],
       "tags": [
        { "key": "piano", "operator": "=", "value": "PP" }
       ]
      }
     ]
    },
    {
     "title": "Dispositivi Piano Terra",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_item",
       "groupBy": [
        { "params": [ "item" ], "type": "tag" }
       ],
       "measurement": "network_ping",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           10
          ],
          "type": "moving_average"
         }
        ]
       ],
       "tags": [
        { "key": "piano", "operator": "=", "value": "PT" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "WIFI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Segnale WIFI",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_item",
     "groupBy": [
      { "params": [ "item" ], "type": "tag" }
     ],
     "measurement": "wifi_signal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSID",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_item",
     "groupBy": [
      { "params": [ "item" ], "type": "tag" }
     ],
     "measurement": "wifi_ssid",
     "query": "SELECT last(\"value\") FROM \"wifi_ssid\" WHERE $timeFilter GROUP BY \"item\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}